name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches:
      - dev
    tags:
      - "v*-beta.*"
      - "v*-rc.*"
  pull_request:
    branches:
      - dev

env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
  MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx/api/v2/package"

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2

    - name: Build
      shell: pwsh
      run: ./Build.ps1 -Build
  Test:
    needs: [Build]
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet.exe
          uses: NuGet/setup-nuget@v1.0.2

        - name: Execute Unit Tests
          shell: pwsh
          run: ./Build.ps1 -UnitTests

        - name: Execute Integration Tests
          shell: pwsh
          run: ./Build.ps1 -IntegrationTests

        - name: Cover Report
          shell: pwsh
          run: ./Build.ps1 -CoverReport

        - name: Codecov
          run: curl -s https://codecov.io/bash | bash -s -- -v -f 'artifacts/Tests/*.OpenCover.xml'

        - name: Codecov 2
          run: curl -s https://codecov.io/bash | bash -s -- -v -f '**/artifacts/Tests/*.OpenCover.xml'

        - name: Codecov 3
          run: curl -s https://codecov.io/bash | bash -s -- -v -f '*.OpenCover.xml'
  Publish:
    needs: [Test]
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2

      - name: Set assembly versions
        shell: pwsh
        run: ./Build.ps1 -SetAssemblyVersion

      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build

      - name: Pack & Publish
        shell: pwsh
        run: ./Build.ps1 -Pack -Publish
